version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
    - "9092:9092"
    volumes:
    - ./secrets:/etc/kafka/secrets
    env_file: 
      - kafka.env
