bootstrap.servers: "localhost:9092"
acks: "all"
retries: 3
batch.size: 16384
linger.ms: 1
buffer.memory: 33554432
# TODO: need to be changed to Avro serializer
# Important: the key and value serializer must match the key and value deserializer of the consumer
#key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
#value.serializer: "org.apache.kafka.common.serialization.StringSerializer"
security.protocol: SSL
ssl.ca.location: "../secrets/ca.crt"


